export const richEditorMenu = {
  menu: [
    { value: "bold", label: "Bold" },
    { value: "italic", label: "Italic" },
    { value: "strike", label: "Strikethrough" },
    { value: "code", label: "Inline code" },
    { value: "clearMarks", label: "Clear marks" },
    { value: "clearNodes", label: "Clear nodes" },
    { value: "paragraph", label: "Paragraph" },
    { value: "h1", label: "Heading 1" },
    { value: "h2", label: "Heading 2" },
    { value: "h3", label: "Heading 3" },
    { value: "h4", label: "Heading 4" },
    { value: "h5", label: "Heading 5" },
    { value: "h6", label: "Heading 6" },
    { value: "bulletList", label: "Bullet list" },
    { value: "orderedList", label: "Ordered list" },
    { value: "codeBlock", label: "Code block" },
    { value: "blockquote", label: "Blockquote" },
    { value: "horizontalRule", label: "Horizontal rule" },
    { value: "hardBreak", label: "Hard break" },
    { value: "undo", label: "Undo" },
    { value: "redo", label: "Redo" },
  ],
};